FROM golang:1.25 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/app ./cmd/app

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /out/app ./app

USER nobody

ENTRYPOINT ["/app/app"]
