version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
  postgres:
    image: postgres:latest # Use the desired PostgreSQL version
    container_name: db
    restart: always
    environment:
      - POSTGRES_USERNAME=main-server
      - POSTGRES_PASSWORD=main-server-password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
