// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/CSKU-Lab/main-server/configs"
	"github.com/CSKU-Lab/main-server/domain/permission"
	"github.com/CSKU-Lab/main-server/domain/registrables"
	"github.com/CSKU-Lab/main-server/domain/services"
	"github.com/CSKU-Lab/main-server/internal/adapters/middlewares"
	sqlx2 "github.com/CSKU-Lab/main-server/internal/adapters/sqlx"
	"github.com/CSKU-Lab/main-server/internal/providers"
	"github.com/gofiber/fiber/v3"
	"github.com/jmoiron/sqlx"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, cfg *configs.Config, db *sqlx.DB, logger *zap.SugaredLogger) (*fiber.App, func(), error) {
	errorHandlerMiddleware := middlewares.NewErrorHandlerMiddleware(cfg, logger)
	user := providers.NewUserRepository(db)
	userPassword := providers.NewUserPasswordRepository(db)
	userGroup := providers.NewUserGroupRepository(db)
	uoWRepository := sqlx2.NewUoWRepository(ctx, db)
	userAuthProviderRepository := providers.NewUserAuthProviderRepository(db)
	userService := services.NewUserService(user, userPassword, userGroup, uoWRepository, userAuthProviderRepository)
	refreshTokenRepository := sqlx2.NewSQLxRefreshTokenRepository(db)
	refreshTokenService := services.NewRefreshTokenService(refreshTokenRepository)
	userGroupService := services.NewUserGroupService(userGroup)
	courseRepository := providers.NewCourseRepository(db)
	courseCreatorRepository := providers.NewCourseCreatorRepository(db)
	queue, err := providers.ProvideRabbitMQ(cfg)
	if err != nil {
		return nil, nil, err
	}
	courseService := services.NewCourseService(courseRepository, courseCreatorRepository, uoWRepository, queue)
	courseEnrollmentRepository := providers.NewCourseEnrollmentRepository(db)
	courseEnrollmentService := services.NewCourseEnrollmentService(courseEnrollmentRepository, courseRepository)
	semesterRepository := sqlx2.NewSqlxSemesterRepository(db)
	sectionRepository := providers.NewSectionRepository(db)
	semesterService := services.NewSemesterService(semesterRepository, sectionRepository, courseRepository)
	sectionLogRepository := providers.NewSectionLogRepository(db)
	sectionLogService := services.NewSectionLogService(sectionLogRepository)
	sectionInstructorRepository := providers.NewSectionInstructorRepository(db)
	sectionStudentRepository := providers.NewSectionStudentRepository(db)
	fileRepository := providers.ProvideMinio(ctx, cfg)
	sectionService := services.NewSectionService(cfg, sectionRepository, uoWRepository, courseRepository, sectionInstructorRepository, sectionStudentRepository, fileRepository, user, semesterRepository, sectionLogService, queue)
	sectionStudentService := services.NewSectionStudentService(sectionStudentRepository, sectionRepository, user)
	tagRepository := sqlx2.NewTagRepository(db)
	tagService := services.NewTagService(tagRepository)
	materialAssetService := services.NewMaterialAssetService(cfg, fileRepository)
	labRepository := providers.NewSqlxLabRepository(db)
	labService := services.NewLabService(labRepository, courseRepository, uoWRepository)
	labSectionRepository := providers.NewSqlxLabSectionRepository(db)
	labSectionService := services.NewLabSectionService(labSectionRepository, uoWRepository, labRepository, sectionRepository, sectionStudentRepository)
	labMaterialRepository := providers.NewSqlxLabMaterialRepository(db)
	materialRepository := providers.NewMaterialRepository(db)
	readMaterialTagRepository := sqlx2.NewReadMaterialTagRepository(db)
	labMaterialService := services.NewLabMaterialService(labMaterialRepository, uoWRepository, labRepository, materialRepository, readMaterialTagRepository, user)
	defaultLabRepository := providers.NewSqlxDefaultLabRepository(db)
	defaultLabService := services.NewDefaultLabService(defaultLabRepository, uoWRepository, courseRepository, labRepository)
	deletedCourseAffected := registrables.NewDeletedCourseAffected(courseRepository, sectionRepository)
	deletedSemesterAffected := registrables.NewDeletedSemesterAffected(semesterRepository, sectionRepository, courseRepository)
	deletedSectionAffected := registrables.NewDeletedSectionAffected(sectionStudentRepository)
	deletedLabAffected := registrables.NewDeletedLabAffected(labRepository, labSectionRepository, labMaterialRepository, defaultLabRepository, uoWRepository)
	deletedLabSectionAffected := registrables.NewDeletedLabSectionAffected(labMaterialRepository, uoWRepository)
	affectedEntitiesFactory := providers.NewPopulatedAffectedEntityFactory(deletedCourseAffected, deletedSemesterAffected, deletedSectionAffected, deletedLabAffected, deletedLabSectionAffected)
	affectedEntitiesService := services.NewAffectedEntitiesService(affectedEntitiesFactory)
	submissionRepository := providers.NewSubmissionRepository(db)
	codeSubmissionRepository := providers.NewCodeSubmissionRepository(db)
	codeMaterialRepository := sqlx2.NewCodeMaterialRepository(db)
	taskServiceClient, cleanup, err := providers.ProvideTaskClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	systemSettingsRepository := providers.NewSystemSettingsRepository(db)
	codeSubmission := registrables.NewCodeSubmission(codeSubmissionRepository, codeMaterialRepository, submissionRepository, taskServiceClient, systemSettingsRepository)
	typingSubmissionRepository := providers.NewTypingSubmissionRepository(db)
	typingMaterialRepository := sqlx2.NewTypingMaterialRepository(db)
	typingSubmission := providers.ProvideTypingSubmission(typingSubmissionRepository, typingMaterialRepository, cfg)
	submissionRegistry := providers.NewPopulatedSubmissionRegistry(codeSubmission, typingSubmission)
	configServiceClient, cleanup2, err := providers.ProvideConfigClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	codeMaterial := registrables.NewCodeMaterial(codeMaterialRepository, taskServiceClient, configServiceClient, systemSettingsRepository)
	typingMaterial := registrables.NewTypingMaterial(typingMaterialRepository)
	documentMaterialRepository := providers.NewDocumentMaterialRepository(db)
	documentMaterial := registrables.NewDocumentMaterial(documentMaterialRepository)
	material := providers.NewPopulatedMaterialRegistry(codeMaterial, typingMaterial, documentMaterial)
	pubSub, err := providers.ProvideRedis(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	systemSettingsService := services.NewSystemSettingsService(systemSettingsRepository)
	submissionServiceArgs := providers.NewSubmissionServiceArgs(submissionRepository, materialRepository, uoWRepository, submissionRegistry, sectionStudentRepository, user, material, sectionRepository, labSectionRepository, labMaterialRepository, codeSubmissionRepository, codeMaterialRepository, pubSub, systemSettingsService)
	submissionService := services.NewSubmissionService(submissionServiceArgs)
	sidebarService := services.NewSidebarService(courseRepository, sectionStudentRepository, labSectionRepository, labMaterialRepository, submissionService)
	gradebookExportService := services.NewGradebookExportService(submissionService)
	materialService := services.NewMaterialService(materialRepository, submissionRepository, readMaterialTagRepository, uoWRepository, user, material, queue)
	searchRepository := providers.NewSearchRepository(db)
	searchService := services.NewSearchService(searchRepository)
	service := permission.NewService(user, courseRepository, courseCreatorRepository, sectionRepository, sectionInstructorRepository, sectionStudentRepository, submissionRepository)
	rateLimiter, err := providers.ProvideRateLimiter(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	graderServiceClient, cleanup3, err := providers.ProvideGraderClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	playgroundHandler := providers.NewPlaygroundHandler(graderServiceClient)
	app := providers.NewFiberApp(cfg, logger, errorHandlerMiddleware, userService, refreshTokenService, userGroupService, courseService, courseEnrollmentService, semesterService, sectionLogService, sectionService, sectionStudentService, tagService, materialAssetService, labService, labSectionService, labMaterialService, defaultLabService, affectedEntitiesService, submissionService, sidebarService, gradebookExportService, materialService, searchService, service, systemSettingsService, configServiceClient, queue, pubSub, rateLimiter, playgroundHandler, typingSubmissionRepository)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
