// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: grader/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_STATUS_UNSPECIFIED           ExecutionStatus = 0
	ExecutionStatus_STATUS_COMPILE_FAILED        ExecutionStatus = 1
	ExecutionStatus_STATUS_RUN_PASSED            ExecutionStatus = 2
	ExecutionStatus_STATUS_RUN_FAILED            ExecutionStatus = 3
	ExecutionStatus_STATUS_TIME_LIMIT_EXCEEDED   ExecutionStatus = 4
	ExecutionStatus_STATUS_MEMORY_LIMIT_EXCEEDED ExecutionStatus = 5
	ExecutionStatus_STATUS_RUNTIME_ERROR         ExecutionStatus = 6
	ExecutionStatus_STATUS_SIGNAL_ERROR          ExecutionStatus = 7
	ExecutionStatus_STATUS_GRADER_ERROR          ExecutionStatus = 8
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_COMPILE_FAILED",
		2: "STATUS_RUN_PASSED",
		3: "STATUS_RUN_FAILED",
		4: "STATUS_TIME_LIMIT_EXCEEDED",
		5: "STATUS_MEMORY_LIMIT_EXCEEDED",
		6: "STATUS_RUNTIME_ERROR",
		7: "STATUS_SIGNAL_ERROR",
		8: "STATUS_GRADER_ERROR",
	}
	ExecutionStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED":           0,
		"STATUS_COMPILE_FAILED":        1,
		"STATUS_RUN_PASSED":            2,
		"STATUS_RUN_FAILED":            3,
		"STATUS_TIME_LIMIT_EXCEEDED":   4,
		"STATUS_MEMORY_LIMIT_EXCEEDED": 5,
		"STATUS_RUNTIME_ERROR":         6,
		"STATUS_SIGNAL_ERROR":          7,
		"STATUS_GRADER_ERROR":          8,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grader_v1_messages_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_grader_v1_messages_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{0}
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_grader_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RunRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RunRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RunResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetRunResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResultRequest) Reset() {
	*x = GetRunResultRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResultRequest) ProtoMessage() {}

func (x *GetRunResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResultRequest.ProtoReflect.Descriptor instead.
func (*GetRunResultRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetRunResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type RunResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	WallTime      float32                `protobuf:"fixed32,4,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResultResponse) Reset() {
	*x = RunResultResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResultResponse) ProtoMessage() {}

func (x *RunResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResultResponse.ProtoReflect.Descriptor instead.
func (*RunResultResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RunResultResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunResultResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *RunResultResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunResultResponse) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *RunResultResponse) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type TestCaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCaseId    string                 `protobuf:"bytes,1,opt,name=test_case_id,json=testCaseId,proto3" json:"test_case_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	WallTime      float32                `protobuf:"fixed32,5,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Memory        int32                  `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseResult) Reset() {
	*x = TestCaseResult{}
	mi := &file_grader_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseResult) ProtoMessage() {}

func (x *TestCaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseResult.ProtoReflect.Descriptor instead.
func (*TestCaseResult) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TestCaseResult) GetTestCaseId() string {
	if x != nil {
		return x.TestCaseId
	}
	return ""
}

func (x *TestCaseResult) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *TestCaseResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TestCaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestCaseResult) GetWallTime() float32 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *TestCaseResult) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type GradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GradeRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GradeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GradedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradedResponse) Reset() {
	*x = GradedResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradedResponse) ProtoMessage() {}

func (x *GradedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradedResponse.ProtoReflect.Descriptor instead.
func (*GradedResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GradedResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetGradeResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeResultRequest) Reset() {
	*x = GetGradeResultRequest{}
	mi := &file_grader_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeResultRequest) ProtoMessage() {}

func (x *GetGradeResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeResultRequest.ProtoReflect.Descriptor instead.
func (*GetGradeResultRequest) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetGradeResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GradeResultResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId     string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status          ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=grader.v1.ExecutionStatus" json:"status,omitempty"`
	TestCaseResults []*TestCaseResult      `protobuf:"bytes,3,rep,name=test_case_results,json=testCaseResults,proto3" json:"test_case_results,omitempty"`
	AvgWallTime     float32                `protobuf:"fixed32,4,opt,name=avg_wall_time,json=avgWallTime,proto3" json:"avg_wall_time,omitempty"`
	AvgMemory       int32                  `protobuf:"varint,5,opt,name=avg_memory,json=avgMemory,proto3" json:"avg_memory,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradeResultResponse) Reset() {
	*x = GradeResultResponse{}
	mi := &file_grader_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResultResponse) ProtoMessage() {}

func (x *GradeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResultResponse.ProtoReflect.Descriptor instead.
func (*GradeResultResponse) Descriptor() ([]byte, []int) {
	return file_grader_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GradeResultResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GradeResultResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNSPECIFIED
}

func (x *GradeResultResponse) GetTestCaseResults() []*TestCaseResult {
	if x != nil {
		return x.TestCaseResults
	}
	return nil
}

func (x *GradeResultResponse) GetAvgWallTime() float32 {
	if x != nil {
		return x.AvgWallTime
	}
	return 0
}

func (x *GradeResultResponse) GetAvgMemory() int32 {
	if x != nil {
		return x.AvgMemory
	}
	return 0
}

var File_grader_v1_messages_proto protoreflect.FileDescriptor

const file_grader_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18grader/v1/messages.proto\x12\tgrader.v1\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"f\n" +
	"\n" +
	"RunRequest\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.grader.v1.FileR\x05files\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"0\n" +
	"\vRunResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"8\n" +
	"\x13GetRunResultRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xb7\x01\n" +
	"\x11RunResultResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\twall_time\x18\x04 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x05R\x06memory\"\xcd\x01\n" +
	"\x0eTestCaseResult\x12 \n" +
	"\ftest_case_id\x18\x01 \x01(\tR\n" +
	"testCaseId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\twall_time\x18\x05 \x01(\x02R\bwallTime\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\x05R\x06memory\"N\n" +
	"\fGradeRequest\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.grader.v1.FileR\x05files\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"3\n" +
	"\x0eGradedResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\":\n" +
	"\x15GetGradeResultRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xf6\x01\n" +
	"\x13GradeResultResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.grader.v1.ExecutionStatusR\x06status\x12E\n" +
	"\x11test_case_results\x18\x03 \x03(\v2\x19.grader.v1.TestCaseResultR\x0ftestCaseResults\x12\"\n" +
	"\ravg_wall_time\x18\x04 \x01(\x02R\vavgWallTime\x12\x1d\n" +
	"\n" +
	"avg_memory\x18\x05 \x01(\x05R\tavgMemory*\x80\x02\n" +
	"\x0fExecutionStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STATUS_COMPILE_FAILED\x10\x01\x12\x15\n" +
	"\x11STATUS_RUN_PASSED\x10\x02\x12\x15\n" +
	"\x11STATUS_RUN_FAILED\x10\x03\x12\x1e\n" +
	"\x1aSTATUS_TIME_LIMIT_EXCEEDED\x10\x04\x12 \n" +
	"\x1cSTATUS_MEMORY_LIMIT_EXCEEDED\x10\x05\x12\x18\n" +
	"\x14STATUS_RUNTIME_ERROR\x10\x06\x12\x17\n" +
	"\x13STATUS_SIGNAL_ERROR\x10\a\x12\x17\n" +
	"\x13STATUS_GRADER_ERROR\x10\bB\x95\x01\n" +
	"\rcom.grader.v1B\rMessagesProtoP\x01Z0github.com/CSKU-Lab/grader-server/grpc/grader/v1\xa2\x02\x03GXX\xaa\x02\tGrader.V1\xca\x02\tGrader\\V1\xe2\x02\x15Grader\\V1\\GPBMetadata\xea\x02\n" +
	"Grader::V1b\x06proto3"

var (
	file_grader_v1_messages_proto_rawDescOnce sync.Once
	file_grader_v1_messages_proto_rawDescData []byte
)

func file_grader_v1_messages_proto_rawDescGZIP() []byte {
	file_grader_v1_messages_proto_rawDescOnce.Do(func() {
		file_grader_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grader_v1_messages_proto_rawDesc), len(file_grader_v1_messages_proto_rawDesc)))
	})
	return file_grader_v1_messages_proto_rawDescData
}

var file_grader_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grader_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grader_v1_messages_proto_goTypes = []any{
	(ExecutionStatus)(0),          // 0: grader.v1.ExecutionStatus
	(*File)(nil),                  // 1: grader.v1.File
	(*RunRequest)(nil),            // 2: grader.v1.RunRequest
	(*RunResponse)(nil),           // 3: grader.v1.RunResponse
	(*GetRunResultRequest)(nil),   // 4: grader.v1.GetRunResultRequest
	(*RunResultResponse)(nil),     // 5: grader.v1.RunResultResponse
	(*TestCaseResult)(nil),        // 6: grader.v1.TestCaseResult
	(*GradeRequest)(nil),          // 7: grader.v1.GradeRequest
	(*GradedResponse)(nil),        // 8: grader.v1.GradedResponse
	(*GetGradeResultRequest)(nil), // 9: grader.v1.GetGradeResultRequest
	(*GradeResultResponse)(nil),   // 10: grader.v1.GradeResultResponse
}
var file_grader_v1_messages_proto_depIdxs = []int32{
	1, // 0: grader.v1.RunRequest.files:type_name -> grader.v1.File
	0, // 1: grader.v1.RunResultResponse.status:type_name -> grader.v1.ExecutionStatus
	0, // 2: grader.v1.TestCaseResult.status:type_name -> grader.v1.ExecutionStatus
	1, // 3: grader.v1.GradeRequest.files:type_name -> grader.v1.File
	0, // 4: grader.v1.GradeResultResponse.status:type_name -> grader.v1.ExecutionStatus
	6, // 5: grader.v1.GradeResultResponse.test_case_results:type_name -> grader.v1.TestCaseResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_grader_v1_messages_proto_init() }
func file_grader_v1_messages_proto_init() {
	if File_grader_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grader_v1_messages_proto_rawDesc), len(file_grader_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grader_v1_messages_proto_goTypes,
		DependencyIndexes: file_grader_v1_messages_proto_depIdxs,
		EnumInfos:         file_grader_v1_messages_proto_enumTypes,
		MessageInfos:      file_grader_v1_messages_proto_msgTypes,
	}.Build()
	File_grader_v1_messages_proto = out.File
	file_grader_v1_messages_proto_goTypes = nil
	file_grader_v1_messages_proto_depIdxs = nil
}
