name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    uses: CSKU-Lab/.github/.github/workflows/docker-publish.yml@main
    with:
      image_name: main-server
      dockerfile_path: docker/Dockerfile.prod
      gitops_paths: apps/main-server/env.libsonnet
      service_name: main-server
    secrets: inherit
